# Generated by Django 4.2.5 on 2023-09-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_favorites_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
