# Generated by Django 4.2.5 on 2023-09-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_alter_realty_latitude_alter_realty_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='house',
            field=models.IntegerField(),
        ),
    ]
