# Generated by Django 4.2.5 on 2023-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_realty_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='house',
            field=models.IntegerField(verbose_name='Дом'),
        ),
    ]
