# Generated by Django 4.2.5 on 2023-09-26 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realty', '0006_alter_realty_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
