# Generated by Django 4.2.5 on 2023-09-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_realty_users_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubUsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rub_usd', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
