# Generated by Django 4.2.5 on 2023-09-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_rubusd'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubusd',
            name='date_get',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
