# Generated by Django 4.2.5 on 2023-09-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_rubusd_date_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubusd',
            name='usd_rub',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
