# Generated by Django 4.2.5 on 2023-09-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0010_rubusd_usd_rub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubusd',
            name='date_get',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
