# Generated by Django 4.2.5 on 2023-10-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0011_alter_rubusd_date_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='total_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
